#!/bin/bash

GW_IP=10.244.0.1
POD_IP=10.244.0.2

exec 2>>/var/log/bash-cni.log
set -x

case $CNI_COMMAND in
ADD)
    host_ifname=veth$POD_IP
    ip link add $CNI_IFNAME type veth peer name $host_ifname
    ip link set $host_ifname master cni0
    ip link set $host_ifname up

    netns=$(basename $CNI_NETNS)
    ip netns add $netns
    ip link set $CNI_IFNAME netns $netns
    ip -n $netns address add $POD_IP/24 dev $CNI_IFNAME
    ip -n $netns link set $CNI_IFNAME up
    ip -n $netns route add default via $GW_IP

    cat <<EOF
{
    "cniVersion": "0.3.1",
    "interfaces": [
        {
            "name": "$CNI_IFNAME",
            "sandbox": "$CNI_NETNS"
        }
    ],
    "ips": [
        {
            "version": "4",
            "address": "$POD_IP/24",
            "interface": 0
        }
    ]
}
EOF
    ;;
DEL)
    netns=$(basename $CNI_NETNS)
    ip -n $netns link delete $CNI_IFNAME
    ip netns delete $netns
    ;;
VERSION)
    cat <<EOF
{
    "cniVersion": "0.3.1",
    "supportedVersions": ["0.3.1"]
}
EOF
    ;;
esac
